"""militaire

Revision ID: 5790ae1e5edb
Revises: e9ca746a63ac
Create Date: 2025-08-29 16:29:22.357063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5790ae1e5edb'
down_revision: Union[str, None] = 'e9ca746a63ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'pocheDeSangs', ['id'])
    op.add_column('reactifs', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reactifs', 'is_deleted')
    op.drop_constraint(None, 'pocheDeSangs', type_='unique')
    # ### end Alembic commands ###
